DROP TABLE Pessoa;
DROP TABLE Preparador;
DROP TABLE Atleta;
DROP TABLE TelefonePessoa;
DROP TABLE TelefoneMedico;
-- DROP TABLE RotinaTreino;
-- DROP TABLE DiasTreino;
-- DROP TABLE Preparo;
-- DROP TABLE Recuperacao;
-- DROP TABLE Treino;
-- DROP TABLE PreparoRotina;
-- DROP TABLE RecuperacaoRotina;
-- DROP TABLE TreinoRotina;
-- DROP TABLE Modalidade;
DROP TABLE Nacao;
DROP TABLE Medico;
-- DROP TABLE TestarDoping;
DROP TABLE Diagnostico;
DROP TABLE MetodoTratamento;
-- DROP TABLE Atendimento;
-- DROP TABLE Tratamento;
DROP TABLE Lesao;
-- DROP TABLE LesaoMedico;
-- DROP TABLE LesaoAtleta;
DROP TABLE TesteDoping;
-- DROP TABLE Consulta;
-- DROP TABLE Sintoma;
-- DROP TABLE Data;
